include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: false
    prefer_single_quotes: true
    sort_constructors_first: true
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_unnecessary_containers: true
    prefer_const_constructors_in_immutables: true
    avoid_relative_lib_imports: true
    prefer_relative_imports: false
    always_use_package_imports: false
    camel_case_types: true
    library_names: true
    file_names: true
    no_duplicate_case_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    unnecessary_const: true
    unnecessary_new: true
    unrelated_type_equality_checks: true

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
